/**
 * Web admin console sessions (roadmap/web-admin.md §8.5, §8.3).
 *
 * Opaque session ids (32-byte random, generated by the web auth layer) map to
 * the authenticated Discord user. Sliding expiry is carried in `expires_at`
 * (bumped on activity, bounded by the absolute cap the auth layer computes
 * from `created_at`); `last_seen_at` is the freshness stamp. Ids are rotated
 * on login and rows are deleted on logout — never updated in place with a new
 * id, so a stolen cookie cannot outlive rotation.
 *
 * `discord_tag` is denormalized display data (name#discriminator / global
 * name snapshot at login), nullable and not authoritative.
 *
 * Indexes (both per §8.5): lookup by user (revocation/listing) and the
 * prune index on `expires_at` for the boot/TTL prune sweep.
 *
 * @param {import("better-sqlite3").Database} db
 */
function up(db) {
  db.exec(`
CREATE TABLE IF NOT EXISTS web_sessions (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL,
  discord_tag  TEXT,
  created_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_web_sessions_user
  ON web_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_web_sessions_expires_at
  ON web_sessions(expires_at);
`);
}

module.exports = { id: "023_web_sessions", up };
