/**
 * View for the Phase-3 ticket ACTIONS surface (roadmap/web-admin.md §8.6
 * "Tickets" row — Mutate tier SENIOR: claim / close / summary regen; subtask
 * 30). One page, three forms; every field is re-validated server-side and
 * every form targets ONE literal mutation path (ticket id rides the BODY —
 * the methodGate matches :guildId as the ONLY param segment, same doctrine
 * as routes/moderation.js's warning_number).
 *
 * COMPOSED ENTIRELY with the escaped-by-default `html` helper (../escape.js)
 * — same XSS contract as views/xpActions and views/moderation: raw() never
 * touches request/DB data, and the PRG flash renders ONLY fixed messages
 * chosen by WHITELISTED SLUG (the raw query value is never echoed — §8.7).
 *
 * TIER: the page renders ONLY for senior+ (route requireTier("senior")) —
 * §8.6 tickets mutate tier. Junior staff keep the Phase-0c READ surfaces
 * (/t index + transcripts, staff-or-participant) untouched; they simply
 * never see controls that would 403 (xpActions "no form that 403s" doctrine).
 */

const { html } = require("../escape");
const { banner } = require("../components");
const { formatTicketRef } = require("../../../core/theme");

/**
 * PRG flash vocabulary (frozen slugs → fixed messages; the *query value* is
 * only ever a map lookup — unknown slugs render nothing). Messages mirror
 * the slash /ticket replies where one exists ("open ticket channel" rule →
 * ticket_not_open, "already archived" → ticket_archived, …). Every refusal
 * states NOTHING was changed, because every refusal IS zero-write.
 */
const FLASH_DONE = Object.freeze({
  ticket_claimed:
    "Ticket claimed — staff owner set and you were added as owner on the ticket (slash-identical).",
  ticket_closed:
    "Ticket closed — the slash soft-close ran (status, close reason, closer). Archive stays slash-only.",
  summary_ai: "Summary regenerated by the AI path (tickets.summarize audited).",
  summary_fallback:
    "Summary regenerated WITHOUT the AI (stats/fallback path) — audited with its source.",
});

const FLASH_ERROR = Object.freeze({
  invalid_ticket_id:
    "Invalid ticket ID — enter the numeric ticket id (digits only). Nothing was changed.",
  ticket_not_found:
    "That ticket does not exist in this server. Nothing was changed.",
  ticket_not_open:
    "This ticket is not open — claim and close only work on an OPEN ticket (mirrors slash). Nothing was changed.",
  close_reason_too_long:
    "Close reason too long — it is capped at the slash bound (1000 characters). Nothing was changed.",
  ticket_archived:
    "This ticket is already archived — summaries regenerate for live tickets only (mirrors slash). Nothing was changed.",
  ai_not_configured:
    "AI not configured — set AI_API_KEY before regenerating summaries. Nothing was changed and no AI call was made.",
  messages_unavailable:
    "No stored messages for this ticket — the web path reads stored rows only and never fetches the channel. Nothing was changed.",
});

/**
 * Whitelist the PRG query: { done, error } where each value is a KNOWN slug
 * or null. Anything else (junk, arrays, hostile strings) is dropped — the
 * flash map lookup is the only consumer.
 * @param {{done?: unknown, error?: unknown}|undefined|null} query
 */
function flashFromQuery(query) {
  const done =
    typeof query?.done === "string" && FLASH_DONE[query.done] ? query.done : null;
  const error =
    typeof query?.error === "string" && FLASH_ERROR[query.error]
      ? query.error
      : null;
  return { done, error };
}

/**
 * Flash banner for the PRG round-trip (frozen message chosen by slug —
 * never the raw query value).
 * @param {{done: string|null, error: string|null}|null} flash
 */
function flashBanner(flash) {
  if (!flash) return html``;
  if (flash.error && FLASH_ERROR[flash.error]) {
    return banner("warn", FLASH_ERROR[flash.error]);
  }
  if (flash.done && FLASH_DONE[flash.done]) {
    return banner("info", FLASH_DONE[flash.done]);
  }
  return html``;
}

/**
 * One open-ticket row: identity + the claim/close form pair. The hidden
 * ticket_id carries the DB row id (the same id the audit rows target —
 * slash resolves tickets by CHANNEL, so the web id is evidenced from the
 * audit targetId + the `tk:sn:<ticketId>` internal reference, not the
 * human T-number).
 * @param {object} input
 * @param {object} input.ticket tickets row (id, ticket_number, creator_user_id, staff_owner_id, reason)
 * @param {string} input.guildId
 * @param {string} input.csrfToken
 * @param {number} input.maxReason MAX_TICKET_REASON (browser hint only)
 */
function renderTicketRow({ ticket, guildId, csrfToken, maxReason }) {
  const gid = encodeURIComponent(guildId);
  const reasonSnippet = String(ticket.reason || "—").slice(0, 120);
  return html`
    <tr>
      <td><code>${ticket.id}</code></td>
      <td>${formatTicketRef(ticket.ticket_number)}</td>
      <td><code>${ticket.creator_user_id}</code></td>
      <td>${ticket.staff_owner_id ? html`<code>${ticket.staff_owner_id}</code>` : html`—`}</td>
      <td class="ticket-reason-cell">${reasonSnippet}</td>
      <td class="ticket-action-cells">
        <form class="ticket-inline-form" method="post" action="/g/${gid}/tickets/claim">
          <input type="hidden" name="_csrf" value="${csrfToken || ""}"/>
          <input type="hidden" name="ticket_id" value="${ticket.id}"/>
          <button type="submit" class="btn btn-write btn-sm">Claim</button>
        </form>
        <form class="ticket-inline-form" method="post" action="/g/${gid}/tickets/close">
          <input type="hidden" name="_csrf" value="${csrfToken || ""}"/>
          <input type="hidden" name="ticket_id" value="${ticket.id}"/>
          <label class="ticket-reason-label"
            >Reason<input
              name="reason"
              type="text"
              maxlength="${maxReason}"
              autocomplete="off"
              placeholder="optional close reason"
          /></label>
          <button type="submit" class="btn btn-write btn-sm">Close</button>
        </form>
      </td>
    </tr>`;
}

/**
 * Senior-only ticket actions page body: open-ticket table with claim/close
 * controls + the standalone summary-regen form (live tickets by id —
 * soft-closed rows stay addressable without a second bounded list query).
 *
 * @param {object} input
 * @param {string} input.guildId server-derived (guildScope snowflake)
 * @param {object[]} input.tickets open-ticket rows (bounded listOpenTickets read)
 * @param {string|null} input.csrfToken
 * @param {{done: string|null, error: string|null}|null} [input.flash]
 * @param {number} input.maxReason MAX_TICKET_REASON bound (rendered as a hint)
 */
function renderTicketActionsBody({ guildId, tickets, csrfToken, flash, maxReason }) {
  const gid = encodeURIComponent(guildId);
  // Array (not .join("")) — html renders SafeString arrays element-by-
  // element; a joined PLAIN string would be escaped as inert text.
  const rows = (tickets || []).map((ticket) =>
    renderTicketRow({ ticket, guildId, csrfToken, maxReason })
  );
  return html`
    ${flashBanner(flash)}
    <section class="panel ticket-actions-panel">
      <h2>Open tickets</h2>
      ${tickets && tickets.length
        ? html`<table class="list-table ticket-actions-table">
            <thead>
              <tr>
                <th>ID</th><th>Ticket</th><th>Requester</th><th>Staff owner</th>
                <th>Reason</th><th>Actions</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>`
        : html`<p class="hint">No open tickets in this server.</p>`}
      <p class="hint">
        Claim and close run the EXACT slash pipelines
        (<code>claimTicket</code> / <code>softCloseTicket</code>: the close
        transition, reason storage, requester DM and staff-only channel pass
        all live inside the feature's own helper) and write the
        <code>tickets.claim</code> / <code>tickets.close</code> audit rows
        with origin <code>web</code>. Archive (transcript + channel delete)
        stays slash-only — §8.6.
      </p>
    </section>
    <section class="panel ticket-summary-panel">
      <h2>Regenerate summary</h2>
      <form class="integ-write-form ticket-summary-form" method="post" action="/g/${gid}/tickets/summarize">
        <input type="hidden" name="_csrf" value="${csrfToken || ""}"/>
        <div class="integ-write-fields">
          <label
            >Ticket ID<input
              name="ticket_id"
              type="text"
              inputmode="numeric"
              autocomplete="off"
              maxlength="12"
              placeholder="numeric ticket id"
          /></label>
        </div>
        <button type="submit" class="btn btn-write">Regenerate summary</button>
      </form>
      <p class="hint">
        Mirrors slash <code>/ticket summarize</code> for LIVE tickets
        (open or soft-closed, never archived) and reads stored message rows
        only — the web path never fetches the channel and NEVER summarizes a
        sensitive ticket (design §8.4: sensitive content never reaches the
        web transport). Without <code>AI_API_KEY</code> the request is
        refused up front with zero AI calls.
      </p>
    </section>`;
}

module.exports = {
  FLASH_DONE,
  FLASH_ERROR,
  flashFromQuery,
  flashBanner,
  renderTicketActionsBody,
};
