/**
 * Build a staff handoff markdown file for a member's notes + warnings.
 */

/**
 * @param {number|null|undefined} ms
 * @returns {string}
 */
function isoTs(ms) {
  if (ms == null) return "—";
  const d = new Date(Number(ms));
  if (Number.isNaN(d.getTime())) return "—";
  return d.toISOString();
}

/**
 * @param {string|null|undefined} text
 * @returns {string}
 */
function block(text) {
  const s = String(text ?? "").trim();
  if (!s) return "_(empty)_";
  // Indent as a markdown blockquote for multi-line safety in plain text readers.
  return s
    .split(/\r?\n/)
    .map((line) => `> ${line}`)
    .join("\n");
}

/**
 * @param {object} opts
 * @param {string} opts.guildId
 * @param {string} [opts.guildName]
 * @param {string} opts.userId
 * @param {string} [opts.userTag]
 * @param {string} opts.exportedById
 * @param {string} [opts.exportedByTag]
 * @param {object[]} opts.warnings
 * @param {object[]} opts.notes
 * @param {number} opts.activeWarnings
 * @param {number} opts.totalWarnings
 * @param {number} opts.activeNotes
 * @param {number} opts.totalNotes
 * @param {Map<number, object>|object} [opts.notesById] related_note_id → note row
 * @param {number} [opts.exportedAt]
 * @returns {string} markdown body
 */
function buildStaffRecordMarkdown(opts) {
  const exportedAt = opts.exportedAt ?? Date.now();
  const guildLabel = opts.guildName
    ? `${opts.guildName} (\`${opts.guildId}\`)`
    : `\`${opts.guildId}\``;
  const subjectLabel = opts.userTag
    ? `${opts.userTag} (\`${opts.userId}\`)`
    : `\`${opts.userId}\``;
  const exporterLabel = opts.exportedByTag
    ? `${opts.exportedByTag} (\`${opts.exportedById}\`)`
    : `\`${opts.exportedById}\``;

  const notesById =
    opts.notesById instanceof Map
      ? opts.notesById
      : new Map(
          Object.entries(opts.notesById || {}).map(([k, v]) => [Number(k), v])
        );

  const lines = [];
  lines.push("# Staff record export");
  lines.push("");
  lines.push(`- **Guild:** ${guildLabel}`);
  lines.push(`- **Subject:** ${subjectLabel}`);
  lines.push(`- **Exported at:** ${isoTs(exportedAt)}`);
  lines.push(`- **Exported by:** ${exporterLabel}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(
    `- Active warnings: **${opts.activeWarnings}** (total including voided: **${opts.totalWarnings}**)`
  );
  lines.push(
    `- Active staff notes: **${opts.activeNotes}** (total including deleted: **${opts.totalNotes}**)`
  );
  lines.push("");
  lines.push("## Warnings");
  lines.push("");

  if (!opts.warnings.length) {
    lines.push("_No warnings on record._");
    lines.push("");
  } else {
    for (const w of opts.warnings) {
      const status = w.voided_at != null ? "VOIDED" : "ACTIVE";
      lines.push(`### W-${w.warning_number} [${status}]`);
      lines.push("");
      lines.push(`- **Issued by:** \`${w.issuer_id}\``);
      lines.push(`- **Created:** ${isoTs(w.created_at)}`);
      if (w.expires_at != null) {
        lines.push(`- **Expires:** ${isoTs(w.expires_at)}`);
      }
      lines.push(`- **Reason:**`);
      lines.push(block(w.reason));
      if (w.evidence_message_url) {
        lines.push(`- **Evidence message:** ${w.evidence_message_url}`);
      }
      if (w.evidence_text) {
        lines.push(`- **Evidence notes:**`);
        lines.push(block(w.evidence_text));
      }
      if (w.related_note_id != null) {
        const linked = notesById.get(Number(w.related_note_id));
        if (linked) {
          lines.push(`- **Linked note:** N-${linked.note_number}`);
        } else {
          lines.push(`- **Linked note id:** ${w.related_note_id}`);
        }
      }
      if (w.voided_at != null) {
        lines.push(`- **Voided:** ${isoTs(w.voided_at)} by \`${w.voided_by}\``);
        lines.push(`- **Void reason:**`);
        lines.push(block(w.void_reason));
      }
      lines.push("");
    }
  }

  lines.push("## Staff notes");
  lines.push("");

  if (!opts.notes.length) {
    lines.push("_No staff notes on record._");
    lines.push("");
  } else {
    for (const n of opts.notes) {
      const status = n.deleted_at != null ? "DELETED" : "ACTIVE";
      lines.push(`### N-${n.note_number} [${status}]`);
      lines.push("");
      lines.push(`- **Author:** \`${n.author_id}\``);
      lines.push(`- **Created:** ${isoTs(n.created_at)}`);
      if (n.edited_at != null) {
        lines.push(
          `- **Edited:** ${isoTs(n.edited_at)} by \`${n.edited_by || "—"}\``
        );
      }
      if (n.deleted_at != null) {
        lines.push(
          `- **Deleted:** ${isoTs(n.deleted_at)} by \`${n.deleted_by || "—"}\``
        );
      }
      lines.push(`- **Content:**`);
      lines.push(block(n.content));
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by Boiler Snake for staff handoff. Do not share with the subject member._"
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Safe filename segment from a snowflake / id.
 * @param {string} userId
 * @param {number} [exportedAt]
 * @returns {string}
 */
function exportFilename(userId, exportedAt = Date.now()) {
  const day = new Date(exportedAt).toISOString().slice(0, 10);
  const safeId = String(userId || "user").replace(/[^\w-]/g, "");
  return `staff-record-${safeId}-${day}.md`;
}

module.exports = {
  buildStaffRecordMarkdown,
  exportFilename,
  isoTs,
};
